### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by cinemast** [LibVNC/vncterm#2]
Hi!

Could you please provide tags and/or releases for this repo? Like in libvncserver. That would be very helpful.

Greetings

**Comment by bk138** [comment]
Done. Thank you for making the effort!

**Comment by cinemast** [comment]
Would it be ok for you to tag it as 0.9.10 instead of 0.1?

**Comment by cinemast** [comment]
Also if possible signed releases would be great.

**Comment by bk138** [comment]
Voila! Sorry didn't have the time to dig for my PGP key...l
