### ISSUE TITLE
Reverse connection

### ISSUE THREAD

**Issue by narcisgarcia** [LibVNC/vncterm#5]
This command works for me:
`x11vnc -connect myclient.example.net`
This command not:
`linuxvnc 1 -connect myclient.example.net`

What is the right syntax?

**Comment by bk138** [comment]
This is not supported (as of now) on linuxvnc, as it only contains a server, not the client part. Feel free to add this via a PR, though :-)

**Comment by narcisgarcia** [comment]
Oh I believed that the "vnc args" were parameters to be passed directly to x11vnc or similar.
x11vnc's -connect option is not for client role but for server role.
Do you know some way to use linuxvnc and force a reverse connection to a listening client?

Thanks.

**Comment by bk138** [comment]
You would have to implement a call to https://github.com/LibVNC/libvncserver/blob/master/rfb/rfb.h#L788 in linuxvnc I guess...
